apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bugtest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bugtest
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/bcbrockway/argocd-presync-sa-not-deleting.git
    targetRevision: develop
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 0
