apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bugtest
  name: bugtest
  namespace: bugtest
spec:
  progressDeadlineSeconds: 20
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: bugtest
  strategy:
    rollingUpdate:
      maxSurge: 15%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bugtest
    spec:
      containers:
      - args:
        - "9999"
        command:
        - sleep
        image: busybox:1.32.0
        imagePullPolicy: IfNotPresent
        name: main
