apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: bugtest
  name: bugtest
  namespace: bugtest
spec:
  progressDeadlineSeconds: 20
  minReadySeconds: 10
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: bugtest
  strategy:
    rollingUpdate:
      maxSurge: 15%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bugtest
    spec:
      containers:
      - command:
        - sh
        - -c
        args:
        - "sleep 30; exit 1"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        image: busybox:1.33.0
        imagePullPolicy: IfNotPresent
        name: main
      serviceAccountName: bugtest
