apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    app.kubernetes.io/name: pre-sync-job
  name: pre-sync-job
  namespace: bugtest
spec:
  template:
    spec:
      containers:
      - args:
        - "10"
        command:
        - sleep
        envFrom:
        - secretRef:
            name: shared-secret
        image: busybox:1.30.0
        imagePullPolicy: IfNotPresent
        name: main
      restartPolicy: Never
      serviceAccountName: shared-sa
  ttlSecondsAfterFinished: 60
