apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    app.kubernetes.io/name: presync-job
  name: presync-job
  namespace: bugtest
spec:
  template:
    spec:
      containers:
      - name: main
        image: busybox:1.33.1
        command:
        - sleep
        args:
        - "5"
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
      serviceAccountName: bugtest
  ttlSecondsAfterFinished: 60
