apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  labels:
    app.kubernetes.io/name: presync-job
  name: presync-job
  namespace: bugtest
spec:
  template:
    spec:
      containers:
      - args:
        - "10"
        command:
        - sleep
        image: busybox:1.30.0
        imagePullPolicy: IfNotPresent
        name: main
      restartPolicy: Never
      serviceAccountName: presync-job
  ttlSecondsAfterFinished: 60
