apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: shared-secret
  name: shared-secret
data:
  FOO: YmFy
