apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: presync-job
  name: presync-job
  namespace: bugtest
automountServiceAccountToken: true
